### ISSUE TITLE
Tags are gone, latest doesn't work

### ISSUE THREAD

**Issue by Kampfbereit** [tutumcloud/tutum-centos#5]
As all tags are gone from the docker hub registry, all dockerfiles requiring tutum/centos:6.5 broke. tutum/centos6 isn't found either.

**Comment by tifayuki** [comment]
Hi @Kampfbereit 

I added the tags back, including `latest`, `centos5`, `centos6`, `centos7`

Thank you for telling us it is broken. 
Sorry for the inconvenience.

**Comment by Kampfbereit** [comment]
Thanks for the quick response!
