### ISSUE TITLE
Failed to get D-Bus connection: No connection to service manager.

### ISSUE THREAD

**Issue by igasi** [tutumcloud/tutum-centos#6]
This error appears when run systemctl status or any attributes for systemctl, in Centos 7.
![screenshot from 2015-09-05 13-01-40](https://cloud.githubusercontent.com/assets/3912749/9700602/5132576c-53ce-11e5-8df0-c31c4032b528.png)

**Comment by fermayo** [comment]
`tutum/centos`, as well as its base image `centos`, don't have an init system. Look at https://github.com/docker/docker/issues/2296 and https://github.com/docker/docker/issues/7459 for background on why.
